### Muhtemelen basit bir proje veya zaten başka bir yerde vardı, ben Kaggle'da göremedim. Varsa o isimleri de kullanır daha büyük bir dataset oluşturulabilinir. 

### Kendi projem için akan veri testi hazırlıyorum. Burada daha önce kaggle'da yayınlanmış 700 K satırlık medikal datalar hali hazırda mevcut. Bunları sanki gerçek hastaymış gibi bazı aralıklarda basacam. Bu esnada daha gerçekçi olması için hasta isimleri uydurmam gerekiyordu. 

* Oluşturduğum fonksiyon muhtemeldir ki işinizi görür görmüyorsa düzenlenmesi kolay olduğunu düşünüyorum.

* Bazı haber kanalları meraklı olabilir çünkü 2008 yılının bilgisayar oyununun şifrelerini bir terör örgütünün şifrelerine ad edebilme yetisine sahipler. 

# Bu notebook içerisinde bulunan isimlerin gerçek hayatla alakası yoktur ve random bir şekilde oluşturulmuştur.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_soyisim = pd.read_csv("../input/turkce-isimler/soy_isimler.csv")
df_kadın = pd.read_csv("../input/turkce-isimler/kadn_isimleri.csv")
df_erkek = pd.read_csv("../input/turkce-isimler/erkek_isimleri.csv")
df_toplu = pd.read_csv("../input/turkce-isimler/karisik_isimler.csv")
df_soyisim.shape,df_kadın.shape,df_erkek.shape, df_toplu.shape

((1653, 1), (69, 1), (48, 1), (117, 1))

### Şimdi iki farklı durum olabilir, Elimizdeki verisetinde hali hazırda cinsiyetleri betimleyen bir öznitelik var veya yok.
#### Öznitelik olmadığını var sayarak bir veri seti uyduralım

In [3]:
df_isim_1= pd.DataFrame()
df_isim_1["yaş"]= np.random.uniform(0,100,100).round(0)
df_isim_1["Z skor"] = np.random.normal(0,2,100)
df_isim_1["Kalsiyum_seviyesi"]= np.random.uniform(8,12,100).round(2)
df_isim_1["PTH"]= np.random.uniform(10,30,100).round(2)
random_cinsiyet= []
random_isim = []
        

## Daha sonra yine 100 kere isim ve soy isim datalarımızda gezinip random atamalar yapalım
for i in range(100):
    soyisim_ = df_soyisim["soyisim"].iloc[np.random.randint(0,1653)]
    tumisim_ = df_toplu["isimler"].iloc[np.random.randint(0,115)]
    isim_ = (tumisim_)+(" ")+(soyisim_)
    random_isim.append(isim_)
    
df_isim_1["random_isim"] = random_isim
df_isim_1

     yaş    Z skor  Kalsiyum_seviyesi    PTH     random_isim
0   42.0  0.690023              10.40  26.59     Ayhan ARPAT
1   35.0 -1.835637              10.81  10.94   Yasemin KENAR
2   93.0  2.277303               9.50  15.07   Dilara GÖRDÜK
3   30.0 -1.742822              10.57  15.05     Çiğdem EVİK
4   87.0 -2.356265               9.36  22.50      Melek YÜCE
..   ...       ...                ...    ...             ...
95  89.0 -1.136254              11.57  26.09    Semra BAYSAL
96  67.0  2.821482              11.30  12.44     Leyla DEMİR
97  51.0 -0.437741               8.29  24.95    Osman KUMBUL
98   9.0  2.030106               8.25  10.55      Berfin ÇAY
99  93.0  2.575604               9.77  15.07  Aysel ELGÖRMÜŞ

[100 rows x 5 columns]

## İkinci bir ihtimal Datasette cinsiyet mevcut olabilir bu durumda

In [4]:
df_isim_2= pd.DataFrame()
df_isim_2["yaş"]= np.random.uniform(0,100,100).round(0)
df_isim_2["Z skor"] = np.random.normal(0,2,100)
df_isim_2["Kalsiyum_seviyesi"]= np.random.uniform(8,12,100).round(2)
df_isim_2["PTH"]= np.random.uniform(10,30,100).round(2)
random_cinsiyet= []
random_isim = []


## Bu kısımların aynısı fonksiyonda da bulunacak
for i in range(df_isim_2.shape[0]):
    # Yani yüz kere for çalışsın 100 farklı cinsiyeti random yaratsın
    if np.random.randint(0,2) == 1:
        random_cinsiyet.append("Kadın")
    else:
        random_cinsiyet.append("Erkek")
df_isim_2["Cinsiyet"] = random_cinsiyet
df_isim_2

     yaş    Z skor  Kalsiyum_seviyesi    PTH Cinsiyet
0   44.0 -4.194263              10.01  14.15    Kadın
1   68.0 -0.416305               8.38  13.67    Kadın
2   67.0  1.829621               9.52  21.99    Erkek
3   77.0 -1.805679              11.50  12.29    Kadın
4   46.0  2.179865              10.28  28.06    Erkek
..   ...       ...                ...    ...      ...
95  54.0 -3.679220               8.94  13.02    Erkek
96  88.0  2.256194              10.98  18.48    Erkek
97  89.0 -0.122888              10.88  13.74    Erkek
98  46.0  1.242596              10.33  23.59    Kadın
99  23.0 -0.432603              11.68  18.86    Kadın

[100 rows x 5 columns]

In [5]:
# Daha gerçekçi olsun diye erkeğe erkek kadına kadın ismi atayabiliriz.
for i in range(df_isim_2.shape[0]):

    soyisim_ = df_soyisim["soyisim"].iloc[np.random.randint(0,1654)]
    kadın_ = df_kadın["kadın_isimleri"].iloc[np.random.randint(0,69)]
    erkek_ = df_erkek["erkek_isimleri"].iloc[np.random.randint(0,48)]

    if df_isim_2["Cinsiyet"].iloc[i] == "Kadın":
        isim_ = (kadın_)+(" ")+(soyisim_)
        random_isim.append(isim_)

    else:
        isim_ = (erkek_)+(" ")+(soyisim_)
        random_isim.append(isim_)
df_isim_2["random_isim"] = random_isim
df_isim_2

     yaş    Z skor  Kalsiyum_seviyesi    PTH Cinsiyet      random_isim
0   44.0 -4.194263              10.01  14.15    Kadın   Fadime SARIGÜL
1   68.0 -0.416305               8.38  13.67    Kadın   Sevim KÖSEOĞLU
2   67.0  1.829621               9.52  21.99    Erkek      Baran MİRZA
3   77.0 -1.805679              11.50  12.29    Kadın      Yağmur AYAZ
4   46.0  2.179865              10.28  28.06    Erkek     Ömer APAYDIN
..   ...       ...                ...    ...      ...              ...
95  54.0 -3.679220               8.94  13.02    Erkek   Halil İBİŞOĞLU
96  88.0  2.256194              10.98  18.48    Erkek       Fatih İLİK
97  89.0 -0.122888              10.88  13.74    Erkek  Muhammed KAZBEK
98  46.0  1.242596              10.33  23.59    Kadın    Hatice FINDIK
99  23.0 -0.432603              11.68  18.86    Kadın   Beyza HALHALLI

[100 rows x 6 columns]

## Fonksiyon hali

In [6]:
# iki farklı durumu deneyeceğim için datasetlerin isimlerini düşürerek alacağım
df_isim_1.drop(columns="random_isim",inplace=True)
df_isim_2.drop(columns="random_isim",inplace=True)

In [7]:
def random_isim_yarat(data,cinsiyetin_varligi=False,cinsiyet_yarat=False):
    dataframe_uzunluğu=data.shape[0]
    random_cinsiyet = []
    random_isim = []
    cinsiyet_var_ = False
    cinsiyet_yarat_ = True
    
    if cinsiyet_var_ == cinsiyetin_varligi:
        
        if cinsiyet_yarat_ == cinsiyet_yarat:
            
            for i in range(dataframe_uzunluğu):
                soyisim_ = df_soyisim["soyisim"].iloc[np.random.randint(0,1653)]
                tumisim_ = df_toplu["isimler"].iloc[np.random.randint(0,115)]
                isim_ = (tumisim_)+(" ")+(soyisim_)
                random_isim.append(isim_)
            data["Random_isimler"] = random_isim
            return data
            
        else:
            
            for i in range(dataframe_uzunluğu):
                if np.random.randint(0,2) == 1:
                    random_cinsiyet.append("Kadın")
                else:
                    random_cinsiyet.append("Erkek")

            data["Cinsiyet"] = random_cinsiyet
            
            for i in range(dataframe_uzunluğu):

                if data["Cinsiyet"].iloc[i] == "Kadın":
                    isim_ = (df_kadın["kadın_isimleri"].iloc[np.random.randint(0,69)])+(" ")+(df_soyisim["soyisim"].iloc[np.random.randint(0,1654)])
                    random_isim.append(isim_)

                else:
                    isim_ = (df_erkek["erkek_isimleri"].iloc[np.random.randint(0,48)])+(" ")+(df_soyisim["soyisim"].iloc[np.random.randint(0,1654)])
                    random_isim.append(isim_)
                    
            data["Random_isimler"] = random_isim
            return data
            
            data["Random_isimler"] = random_isim
            return data
        
    else:

        for i in range(dataframe_uzunluğu):

            if data["Cinsiyet"].iloc[i] == "Kadın":
                isim_ = (df_kadın["kadın_isimleri"].iloc[np.random.randint(0,69)])+(" ")+(df_soyisim["soyisim"].iloc[np.random.randint(0,1654)])
                random_isim.append(isim_)

            else:
                isim_ = (df_erkek["erkek_isimleri"].iloc[np.random.randint(0,48)])+(" ")+(df_soyisim["soyisim"].iloc[np.random.randint(0,1654)])
                random_isim.append(isim_)

        data["Random_isimler"] = random_isim
        return data

In [8]:
# ilk datada cinsiyetler mevcut değildi
# Deney 1 Cinsiyet yarat ve buna göre isim ata
deney1 = random_isim_yarat(df_isim_1,cinsiyetin_varligi=False,cinsiyet_yarat=False)
deney1

     yaş    Z skor  Kalsiyum_seviyesi    PTH Cinsiyet        Random_isimler
0   42.0  0.690023              10.40  26.59    Kadın        Meryem ALPAYCI
1   35.0 -1.835637              10.81  10.94    Erkek           Burak PEKER
2   93.0  2.277303               9.50  15.07    Kadın            Ela GÜLŞEN
3   30.0 -1.742822              10.57  15.05    Erkek         Umut GÜLDAMLA
4   87.0 -2.356265               9.36  22.50    Erkek       Berat ÖZCANOĞLU
..   ...       ...                ...    ...      ...                   ...
95  89.0 -1.136254              11.57  26.09    Kadın  Özlem KARAMAHMUTOĞLU
96  67.0  2.821482              11.30  12.44    Kadın         Nisanur OYNAK
97  51.0 -0.437741               8.29  24.95    Kadın      Sultan YENİDOĞAN
98   9.0  2.030106               8.25  10.55    Kadın           Merve BAKAY
99  93.0  2.575604               9.77  15.07    Erkek          Serkan GÜNEY

[100 rows x 6 columns]

In [9]:
# Deney 2 Cinsiyet yaratma ama isim döndür
deney2 = random_isim_yarat(df_isim_1,cinsiyetin_varligi=False,cinsiyet_yarat=True)
deney2

     yaş    Z skor  Kalsiyum_seviyesi    PTH Cinsiyet    Random_isimler
0   42.0  0.690023              10.40  26.59    Kadın      Hatice PIRTI
1   35.0 -1.835637              10.81  10.94    Erkek     Hatice ÇAĞLAR
2   93.0  2.277303               9.50  15.07    Kadın         Umut ONUK
3   30.0 -1.742822              10.57  15.05    Erkek       Furkan SADİ
4   87.0 -2.356265               9.36  22.50    Erkek   Yağmur KALYONCU
..   ...       ...                ...    ...      ...               ...
95  89.0 -1.136254              11.57  26.09    Kadın        Nuray İZCİ
96  67.0  2.821482              11.30  12.44    Kadın       Semra ÖZÇAY
97  51.0 -0.437741               8.29  24.95    Kadın     Oğuzhan DURUK
98   9.0  2.030106               8.25  10.55    Kadın    Oğuzhan BİLGİN
99  93.0  2.575604               9.77  15.07    Erkek  Serhat YENİDOĞAN

[100 rows x 6 columns]

In [10]:
# Deney 3 Zaten cinsiyetimiz var buna göre isim listesi döndür
deney3 = random_isim_yarat(df_isim_2,cinsiyetin_varligi=True,cinsiyet_yarat=False)
deney3

     yaş    Z skor  Kalsiyum_seviyesi    PTH Cinsiyet    Random_isimler
0   44.0 -4.194263              10.01  14.15    Kadın  Aleyna ABACIOĞLU
1   68.0 -0.416305               8.38  13.67    Kadın       Seda BAYTAN
2   67.0  1.829621               9.52  21.99    Erkek       Osman ÖRDEK
3   77.0 -1.805679              11.50  12.29    Kadın        Pınar ORAK
4   46.0  2.179865              10.28  28.06    Erkek       Oğuzhan SAĞ
..   ...       ...                ...    ...      ...               ...
95  54.0 -3.679220               8.94  13.02    Erkek       Fatih AKSOY
96  88.0  2.256194              10.98  18.48    Erkek     Emrah KİRİŞCİ
97  89.0 -0.122888              10.88  13.74    Erkek      Ahmet GERDAN
98  46.0  1.242596              10.33  23.59    Kadın      Ayşe KOYUNCU
99  23.0 -0.432603              11.68  18.86    Kadın         Ela AYMAN

[100 rows x 6 columns]

## Ek önerilere açığım, umarım işinize yarar